# Generated by Django 3.0.1 on 2020-01-06 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20200106_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='Album',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='web.Album'),
            preserve_default=False,
        ),
    ]
