# Generated by Django 3.0.1 on 2020-01-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20200106_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='songs_year',
            new_name='songs_release_date_year',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='songs_name',
            new_name='songs_singer_name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='songs_singer',
            new_name='songs_title_name',
        ),
        migrations.AddField(
            model_name='album',
            name='albums_image',
            field=models.ImageField(default='', upload_to='image/'),
        ),
        migrations.AddField(
            model_name='song',
            name='songs_image',
            field=models.ImageField(default='', upload_to='image/'),
        ),
    ]
